### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by R4H4T069** [emarsden/pssh-box-wasm#6]
![Uploading Screenshot 2024-08-23 210326.png…]()

**Comment by emarsden** [comment]
Hi, could you please reupload your screenshot, or share the relevant data in text, the image link is not working.

**Comment by R4H4T069** [comment]
<img width="900" alt="Screenshot 2024-08-23 210326" src="https://github.com/user-attachments/assets/82313d1c-42e1-448e-a5be-a8f203916bd5">
Bro I tried to get a Crunchyroll Widevine license But It give me this error

**Comment by emarsden** [comment]
It looks like the CrunchyRoll license server is returning invalid protobuf responses. I'm not too surprised, because they seem to use various non-standard adaptations to DASH streaming (e.g. their PlayReady PSSH boxes are not correctly formatted).

This service is really unsuited to debugging a licence message flow, I'm afraid. Please try using pywidevine directly for any debugging.
